# Prediction of sales

### Problem Statement
[The dataset](https://drive.google.com/file/d/1B07fvYosBNdIwlZxSmxDfeAf9KaygX89/view?usp=sharing) represents sales data for 1559 products across 10 stores in different cities. Also, certain attributes of each product and store are available. The aim is to build a predictive model and find out the sales of each product at a particular store.

|Variable|Description|
|: ------------- |:-------------|
|Item_Identifier|Unique product ID|
|Item_Weight|Weight of product|
|Item_Fat_Content|Whether the product is low fat or not|
|Item_Visibility|The % of total display area of all products in a store allocated to the particular product|
|Item_Type|The category to which the product belongs|
|Item_MRP|Maximum Retail Price (list price) of the product|
|Outlet_Identifier|Unique store ID|
|Outlet_Establishment_Year|The year in which store was established|
|Outlet_Size|The size of the store in terms of ground area covered|
|Outlet_Location_Type|The type of city in which the store is located|
|Outlet_Type|Whether the outlet is just a grocery store or some sort of supermarket|
|Item_Outlet_Sales|Sales of the product in the particulat store. This is the outcome variable to be predicted.|

Please note that the data may have missing values as some stores might not report all the data due to technical glitches. Hence, it will be required to treat them accordingly.



### Explore the problem in following stages:

1. Hypothesis Generation – understanding the problem better by brainstorming possible factors that can impact the outcome
2. Data Exploration – looking at categorical and continuous feature summaries and making inferences about the data.
3. Data Cleaning – imputing missing values in the data and checking for outliers
4. Feature Engineering – modifying existing variables and creating new ones for analysis
5. Model Building – making predictive models on the data

In [1]:
import pandas as pd

#Read files:
data = pd.read_csv("regression_exercise.csv", delimiter=',')
data

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [2]:
# Filling missing values for Item_Weight variable
for type in set(data.Item_Type):
    data.loc[data['Item_Type'] == type, 'Item_Weight'] = data.loc[data['Item_Type'] == type, 'Item_Weight'].fillna(data['Item_Weight'][data['Item_Type'] == type].mean())

In [3]:
# Filling missing values for Outlet_Size variable
data.loc[:,'Outlet_Size'] = data['Outlet_Size'].fillna('Unknown')

In [4]:
data

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Unknown,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,Unknown,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

## 4. Feature Engineering

1. Resolving the issues in the data to make it ready for the analysis.
2. Create some new variables using the existing ones.

### Create a broad category of Type of Item

Item_Type variable has many categories which might prove to be very useful in analysis. Look at the Item_Identifier, i.e. the unique ID of each item, it starts with either FD, DR or NC. If you see the categories, these look like being Food, Drinks and Non-Consumables. Use the Item_Identifier variable to create a new column

In [6]:
Item_Category = []
for item in data['Item_Identifier']:
    Item_Category.append(item[0:2])

data['Item_Category'] = Item_Category

In [7]:
data.loc[data['Item_Category'] == 'FD', 'Item_Category'] = 'Food'
data.loc[data['Item_Category'] == 'DR', 'Item_Category'] = 'Drinks'
data.loc[data['Item_Category'] == 'NC', 'Item_Category'] = 'Non-Consumables'

### Determine the years of operation of a store

Make a new column depicting the years of operation of a store (i.e. how long the store exists).

In [8]:
data['Outlet_Operation_Years'] = 2020 - data['Outlet_Establishment_Year']

### Modify categories of Item_Fat_Content

There are difference in representation in categories of Item_Fat_Content variable. This should be corrected.

In [9]:
data.loc[data['Item_Fat_Content'].isin(('LF', 'Low Fat', 'low fat')), 'Item_Fat_Content'] = 'Low Fat'
data.loc[data['Item_Fat_Content'].isin(('Regular', 'reg')), 'Item_Fat_Content'] = 'Regular'

There are some non-consumables as well and a fat-content should not be specified for them. Create a separate category for such kind of observations.

In [10]:
# Setting item fat content variable for non-consumables to NA (Not Applicable)
data.loc[data['Item_Category'] == 'Non-Consumables', 'Item_Fat_Content'] = 'NA'

### Numerical and One-Hot Encoding of Categorical variables

Since scikit-learn algorithms accept only numerical variables, we need to convert all categorical variables into numeric types. 

- if the variable is Ordinal we can simply map its values into numbers
- if the variable is Nominal (we cannot sort the values) we need to One-Hot Encode them --> create dummy variables

In [11]:
# ordinal variables
data = data.replace({'Item_Fat_Content' : {'NA' : 0, 'Low Fat' : 1, 'Regular' : 2},
                     'Outlet_Size' : {'Unknown' : 0, 'Small' : 1, 'Medium' : 2, 'High' : 3}}
                   )

In [12]:
# Item category dummy variables
data.loc[data['Item_Category'] == 'Drinks', 'Drinks'] = 1
data.loc[data['Item_Category'] != 'Drinks', 'Drinks'] = 0

data.loc[data['Item_Category'] == 'Food', 'Food'] = 1
data.loc[data['Item_Category'] != 'Food', 'Food'] = 0

#outlet identifier dummy variables
data.loc[data['Outlet_Identifier'] == 'OUT010', 'OUT010'] = 1
data.loc[data['Outlet_Identifier'] != 'OUT010', 'OUT010'] = 0

data.loc[data['Outlet_Identifier'] == 'OUT013', 'OUT013'] = 1
data.loc[data['Outlet_Identifier'] != 'OUT013', 'OUT013'] = 0

data.loc[data['Outlet_Identifier'] == 'OUT017', 'OUT017'] = 1
data.loc[data['Outlet_Identifier'] != 'OUT017', 'OUT017'] = 0

data.loc[data['Outlet_Identifier'] == 'OUT018', 'OUT018'] = 1
data.loc[data['Outlet_Identifier'] != 'OUT018', 'OUT018'] = 0

data.loc[data['Outlet_Identifier'] == 'OUT019', 'OUT019'] = 1
data.loc[data['Outlet_Identifier'] != 'OUT019', 'OUT019'] = 0

data.loc[data['Outlet_Identifier'] == 'OUT027', 'OUT027'] = 1
data.loc[data['Outlet_Identifier'] != 'OUT027', 'OUT027'] = 0

data.loc[data['Outlet_Identifier'] == 'OUT035', 'OUT035'] = 1
data.loc[data['Outlet_Identifier'] != 'OUT035', 'OUT035'] = 0

data.loc[data['Outlet_Identifier'] == 'OUT045', 'OUT045'] = 1
data.loc[data['Outlet_Identifier'] != 'OUT045', 'OUT045'] = 0

data.loc[data['Outlet_Identifier'] == 'OUT046', 'OUT046'] = 1
data.loc[data['Outlet_Identifier'] != 'OUT046', 'OUT046'] = 0

#outlet location type dummy variables
data.loc[data['Outlet_Location_Type'] == 'Tier 1', 'Tier_1'] = 1
data.loc[data['Outlet_Location_Type'] != 'Tier 1', 'Tier_1'] = 0

data.loc[data['Outlet_Location_Type'] == 'Tier 2', 'Tier_2'] = 1
data.loc[data['Outlet_Location_Type'] != 'Tier 2', 'Tier_2'] = 0

#outlet type
data.loc[data['Outlet_Type'] == 'Grocery Store', 'Grocery_Store'] = 1
data.loc[data['Outlet_Type'] != 'Grocery Store', 'Grocery_Store'] = 0

data.loc[data['Outlet_Type'] == 'Supermarket Type1', 'Supermarket_Type1'] = 1
data.loc[data['Outlet_Type'] != 'Supermarket Type1', 'Supermarket_Type1'] = 0

data.loc[data['Outlet_Type'] == 'Supermarket Type2', 'Supermarket_Type2'] = 1
data.loc[data['Outlet_Type'] != 'Supermarket Type2', 'Supermarket_Type2'] = 0

data

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,...,OUT019,OUT027,OUT035,OUT045,OUT046,Tier_1,Tier_2,Grocery_Store,Supermarket_Type1,Supermarket_Type2
0,FDA15,9.300,1,0.016047,Dairy,249.8092,OUT049,1999,2,Tier 1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,DRC01,5.920,2,0.019278,Soft Drinks,48.2692,OUT018,2009,2,Tier 3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,FDN15,17.500,1,0.016760,Meat,141.6180,OUT049,1999,2,Tier 1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,FDX07,19.200,2,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,0,Tier 3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,NCD19,8.930,0,0.000000,Household,53.8614,OUT013,1987,3,Tier 3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,1,0.056783,Snack Foods,214.5218,OUT013,1987,3,Tier 3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8519,FDS36,8.380,2,0.046982,Baking Goods,108.1570,OUT045,2002,0,Tier 2,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
8520,NCJ29,10.600,0,0.035186,Health and Hygiene,85.1224,OUT035,2004,1,Tier 2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
8521,FDN46,7.210,2,0.145221,Snack Foods,103.1332,OUT018,2009,2,Tier 3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8522,DRG01,14.800,1,0.044878,Soft Drinks,75.4670,OUT046,1997,1,Tier 1,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0

All variables should be by now numeric

### Exporting Data
you can save the processed data to disk

In [14]:
data = data.drop(['Item_Identifier', 'Item_Type', 'Item_Category', 'Outlet_Establishment_Year', 'Outlet_Identifier',
                 'Outlet_Location_Type', 'Outlet_Type'], axis = 1)

In [15]:
pd.DataFrame.to_csv(data, 'regression_exercise_modified.csv')